### ISSUE TITLE
calling a device object from host?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/mallocMC#113]
mallocMC defines a global object as default heap on device [see here](https://github.com/ComputationalRadiationPhysics/mallocMC/blob/8980ead57c6282a305b21ed229c844d498024fae/src/include/mallocMC/mallocMC_overwrites.hpp#L48)
```C++
namespace mallocMC{                                                             \
  typedef MALLOCMC_USER_DEFINED_TYPENAME mallocMCType;                           \
                                                                               \
MAMC_ACCELERATOR mallocMCType mallocMCGlobalObject;                               \
...
```

Than a host function is defined to initialize the heap
```C++
MAMC_HOST void* initHeap(                                                       \
    size_t heapsize = 8U*1024U*1024U,                                          \
    mallocMCType &p = mallocMCGlobalObject                                       \
    )                                                                          \
{                                                                              \
    return p.initHeap(heapsize);                                               \
}
``` 
If `p.initHeap(...)` is called than it should be a invalid memory access.

@slizzered Is this a **BUG** or is there a reason why it not crash at compile time?

**Comment by ax3l** [comment]
@slizzered let me raise awareness for this since we need to solve this before the next PIConGPU release (which will introduce mallocMC).

**Comment by Flamefire** [comment]
I tried to dig into that issue with a couple of testcodes. What you basically assume: There is an allocation on the host of the same size as the one on the device and this can be read and written. What I found:

- Accessing the device variable directly causes a warning, that you "cannot [read/write it] in a host function"
- Accessing it in an obfuscated way (passing pointer or reference to a function) issues no warning and seems to work (warning is not possible unless effort is done to trace that usage through some calls)
- The static address of global device and host variables is in different memory regions. So it is unlikely to overwrite a host struct ***in the current CUDA implementation***
- Declaring 2 device variables and taking their addresses shows the correct space between them ***in the current CUDA implementation***, further supporting the assumption
- There seems to be no official documentation on that besides, that it is not allowed to access those on the host and you need to get the device address by the `cudaGetSymbolAddress` function (http://stackoverflow.com/questions/34041372/access-cuda-global-device-variable-from-host)
- For the unified memory space model it would (maybe) be possible, that the address is the same on device and host but pointing to device memory in both cases. So `cudaGetSymbolAddress` returns the same address. But this is unlikely due to the requirement, that it must be (seems to be) an actual symbol on the host.

So although all test results so far show, that this usage is valid and produces correct results, it is likely that this is undefined behaviour but works in current CUDA versions. We probably have to ask NVIDIA to tell for sure.
