### ISSUE TITLE
CMake: 2.8.12.2+

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/mallocMC#92]
Since the default CMake [module](https://github.com/ComputationalRadiationPhysics/cmake-modules) does now require cmake 2.8.12.2+, one could push the cmake versions for the project itself (`cmake_minimum_required`) and the documentation of required software itself to the same version to avoid confusion for users.

(Aka "I installed in successfully but my project does not work with it..." -> let's force a CMake version that will hold the full way to a project.)

**Comment by slizzered** [comment]
Sounds like a good idea to improve usability :+1:

Just a remark: We could think about using a [configFile](http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#config-file-packages) instead of a [FindModule](http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#find-module-packages) in the future, since mallocMC already uses CMake. It looks to me like the concept is not 100% polished yet for non-Windows platforms ([see](http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#system-package-registry)), but might be a nice alternative because we can ship the find-script directly with the mallocMC package.

**Comment by ax3l** [comment]
regarding configFiles: afaik and what I got as feedback in the mailing lists, modules are kind of deprecated: also the mainline does not prefer accepting new modules for software.

I am still not 100% overwhelmed by cmake config files, since they do not solve the chicken-egg problem of finding the install in the first place (at least how I understood them). because in the end, one still needs to provide a hint (e.g., via CMAKE_PREFIX_PATH) to find the already installed config file.
Nevertheless, I guess they make multi-platform support way easier by relying on that and taking the system default from the system cmake instead of looking up all system paths for all systems in a module.

**Comment by slizzered** [comment]
when you say "modules", are you talking about FindModule stuff like the one we worked on?

The problem with finding the config files for a project appears to be somewhat solved under Windows (canonical place in the windows registry), but there is no good solution available for Linux yet.** So for now, configFiles are not the ideal solution that they might become in the future.


-------

** on a per-user basis, configs can be placed under `~/.cmake/packages`, but sadly there is no such default folder on system-level

**Comment by ax3l** [comment]
> when you say "modules", are you talking about FindModule stuff like the one we worked on?

yes. cmake `find_package` modules, stored under `$CMAKE_SHARED/Modules/`.

> there is no good solution available for Linux yet.**

yes, that place in $HOME was what I saw too, nevertheless, I remember that setting up a useful environment for a cluster / module system is kind-of painful/not yet possible.
